name: assistant
description: work assistant.
version: 1.0.5+9

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_fonts: ^2.1.0
  charts_flutter: ^0.11.0
  data_table_2: ^2.1.1
  url_launcher: ^6.0.12
  flutter_lints: ^1.0.0
  clipboard: ^0.1.3
  fluttertoast: ^8.0.8
  yaml: ^3.1.0
  shared_preferences: ^2.0.8
  retrofit: ^2.0.1
  json_annotation: ^4.3.0
  path_provider: ^2.0.5
  window_manager: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.1.4
  retrofit_generator: ^2.0.1+2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/config/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
