name: assistant
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  system_theme: ^2.0.0
  bitsdojo_window: ^0.1.1+1
  window_manager: ^0.2.1
  url_strategy: ^0.2.0
  url_launcher: ^6.0.15
  clipboard: ^0.1.3
  msix: ^3.5.1
  email_validator: ^2.0.1
  shared_preferences: ^2.0.13
  logger: ^1.1.0
  path_provider: ^2.0.5
  file_picker: ^4.5.0
  process_run: ^0.12.3+2
  retrofit: ^3.0.1+1
  json_annotation: ^4.3.0
  flutter_markdown: ^0.6.9
  desktop_window: ^0.4.0
  encrypt: ^5.0.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  build_runner: "2.1.10"
  json_serializable: ">4.4.0"

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/icons/
    - assets/logo/

msix_config:
  display_name: Assistant
  publisher_display_name: Moseoh
  identity_name: Moseoh.Assistant
  msix_version: 1.0.6.3
  store: false
  logo_path: D:\DEV\Code\Project\assistant\flutter\assets\logo\flutter.png
  output_path: D:\DEV\Code\Project\assistant\flutter
  capabilities: "internetClient"
  certificate_path: D:\DEV\Code\Project\assistant\flutter\certificate\Moseoh.pfx
  certificate_password: qwe123
