name: assistant
description: work assistant.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  google_fonts: ^2.1.0
  charts_flutter: ^0.11.0
  data_table_2: ^2.1.1
  url_launcher: ^6.0.12
  flutter_lints: ^1.0.0
  clipboard: ^0.1.3
  fluttertoast: ^8.0.8
  yaml: ^3.1.0
  shared_preferences: ^2.0.13
  retrofit: ^2.0.1
  json_annotation: ^4.3.0
  path_provider: ^2.0.5
  window_manager: ^0.0.5
  msix: ^2.8.17
  fluent_ui: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.1.4
  retrofit_generator: ^2.0.1+2

flutter:
  uses-material-design: true
  assets:
    - pubspec.yaml
    - assets/icons/
    - assets/logo/
  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: fonts/AppleSDGothicNeoH.ttf
          weight: 900
        - asset: fonts/AppleSDGothicNeoEB.ttf
          weight: 800
        - asset: fonts/AppleSDGothicNeoB.ttf
          weight: 700
        - asset: fonts/AppleSDGothicNeoM.ttf
          weight: 600
        - asset: fonts/AppleSDGothicNeoR.ttf
        - asset: fonts/AppleSDGothicNeoL.ttf
          weight: 400
        - asset: fonts/AppleSDGothicNeoUL.ttf
          weight: 300
        - asset: fonts/AppleSDGothicNeoT.ttf
          weight: 200

msix_config:
  display_name: Assistant
  publisher_display_name: Moseoh
  identity_name: Moseoh.Assistant
  msix_version: 1.0.5.5
  store: false
  logo_path: D:\DEV\Code\Project\assistant\flutter\assets\logo\flutter.png
  output_path: D:\DEV\Code\Project\assistant\flutter
  capabilities: "internetClient"
  certificate_path: D:\DEV\Code\Project\assistant\flutter\certificate\Moseoh.pfx
  certificate_password: qwe123