spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/assistant
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwe123
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

logging:
  level:
    "[org.springframework.web]": debug
